### ISSUE TITLE
Argument 2 passed to JMS\\Serializer\\Handler\\ArrayCollectionHandler::serializeCollection() must implement interface Doctrine\\Common\\Collections\\Collection, array given,

### ISSUE THREAD

**Issue by bahatron** [schmittjoh/JMSSerializerBundle#683]
I'm sudendly experiencing this issue after clearing cache and composer install

`jms/serializer-bundle`: `2.4.2`
`symfony`: `4.1.2`
`environment`: `7.2.2-3+ubuntu16.04.1+deb.sury.org+1`

```
Argument 2 passed to JMS\\Serializer\\Handler\\ArrayCollectionHandler::serializeCollection() must implement interface Doctrine\\Common\\Collections\\Collection, array given, called in \/home\/forge\/supplier.atedev.co.uk\/vendor\/jms\/serializer\/src\/JMS\/Serializer\/GraphNavigator.php on line 184
```

stack
```
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 2 passed to JMS\Serializer\Handler\ArrayCollectionHandler::serializeCollection() must implement interface Doctrine\Common\Collections\Collection, array given, called in /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php on line 184
#19 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/Handler/ArrayCollectionHandler.php(56): serializeCollection
#18 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php(184): accept
#17 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php(145): visitProperty
#16 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php(248): accept
#15 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php(97): visitArray
#14 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php(134): accept
#13 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(177): visit
#12 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(96): JMS\Serializer\{closure}
#11 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(0): call_user_func
#10 /home/forge/supplier.atedev.co.uk/vendor/phpoption/phpoption/src/PhpOption/Some.php(89): map
#9 /home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(99): serialize
#8 /home/forge/supplier.atedev.co.uk/src/Service/Util/AteSerializer.php(53): serialize
#7 /home/forge/supplier.atedev.co.uk/src/Controller/AteController.php(60): _jsonResponse
#6 /home/forge/supplier.atedev.co.uk/src/Controller/AteController.php(87): _successResponse
#5 /home/forge/supplier.atedev.co.uk/src/Controller/AteController.php(92): _response
#4 /home/forge/supplier.atedev.co.uk/src/Controller/Api/Supplier/SupplierController.php(55): getSupplier
#3 /home/forge/supplier.atedev.co.uk/vendor/symfony/http-kernel/HttpKernel.php(149): handleRaw
#2 /home/forge/supplier.atedev.co.uk/vendor/symfony/http-kernel/HttpKernel.php(66): handle
#1 /home/forge/supplier.atedev.co.uk/vendor/symfony/http-kernel/Kernel.php(188): handle
#0 index.php(37): null
```

context 

`/home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/Serializer.php in serialize at line 99`
```
collection | [Object ATE\SupplierDomain\Component\Listing\Listing]
-- | --
context | Object JMS\Serializer\SerializationContext
type | {name: ArrayCollection, params: [{}]}
visitor | Object JMS\Serializer\JsonSerializationVisitor
```

`/home/forge/supplier.atedev.co.uk/vendor/jms/serializer/src/JMS/Serializer/Handler/ArrayCollectionHandler.php in serializeCollection at line 56`
```

collection | [Object ATE\SupplierDomain\Component\Listing\Listing]
-- | --
context | Object JMS\Serializer\SerializationContext
type | {name: ArrayCollection, params: [{}]}
visitor | Object JMS\Serializer\JsonSerializationVisitor
```

**Comment by goetas** [comment]
can you share your entity where the collection is present?

**Comment by bahatron** [comment]
```
<?php

namespace ATE\SupplierDomain\Component\Listing;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Doctrine\Common\Collections\ArrayCollection;
use ATE\SupplierDomain\Model\Entity\Supplier\Supplier;
use Symfony\Component\Validator\Constraints as Assert;
use ATE\SupplierDomain\Model\Entity\Keyword\AbstractKeyword;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation as SymfonySerializer;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity("id")
 * @Serializer\ExclusionPolicy("none")
 */
class Listing
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *
     * @Serializer\Groups({"private", "original"})
     */
    private $id;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     *
     * @Assert\Type("boolean")
     *
     * @Serializer\Type("boolean")
     */
    private $active = false;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *
     * @Assert\Type("integer")
     *
     * @Serializer\Type("integer")
     */
    private $coverage = 40;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *
     * @Assert\Type("integer")
     *
     * @Serializer\Type("integer")
     */
    private $node;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @Assert\DateTime()
     *
     * Serializer\Type("DateTime")
     */
    private $approvedAt;

    /**
     * @ORM\Column(type="datetime", nullable=false)
     *
     * @Assert\DateTime()
     * @Assert\NotBlank()
     *
     * @Serializer\ReadOnly
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @Assert\DateTime()
     *
     * @Serializer\ReadOnly
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="ATE\SupplierDomain\Model\Entity\Supplier\Customer", inversedBy="listings")
     *
     * @Assert\NotBlank()
     *
     * @Serializer\Exclude
     *
     * @SymfonySerializer\MaxDepth(1)
     */
    private $supplier;

    /**
     * @ORM\ManyToMany(targetEntity="ATE\SupplierDomain\Model\Entity\Keyword\AbstractKeyword", inversedBy="listings", cascade={"all"})
     * @ORM\JoinTable(name="listing_keywords",
     *      joinColumns={@ORM\JoinColumn(name="listing_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="keyword_id", referencedColumnName="id")}
     * )
     *
     * @Serializer\ReadOnly
     * @Serializer\Type("ArrayCollection<ATE\SupplierDomain\Model\Entity\Keyword\AbstractKeyword>")
     */
    private $keywords;

    /**
     * @Serializer\PostDeserialize()
     */
    public function __construct()
    {
        $this->createdAt = $this->createdAt ?: new \DateTime();

        $this->keywords = new ArrayCollection();
    }
 //.....
}

**Comment by goetas** [comment]
No, i need the entity where a collection of `Listing` is present

**Comment by bahatron** [comment]
sorry
```
<?php

namespace ATE\SupplierDomain\Model\Entity\Supplier;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use ATE\SupplierDomain\Component\Listing\Listing;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 */
class Customer extends Supplier
{
    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @Assert\DateTime()
     *
     * @JMS\Groups("original")
     * @JMS\Type("DateTime")
     */
    private $signedTerms;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @Assert\DateTime()
     *
     * @JMS\Groups({"original"})
     * @JMS\Type("DateTime")
     */
    private $willReceiveMarketingEmails;

    /**
     * @ORM\OneToMany(targetEntity="ATE\SupplierDomain\Component\Listing\Listing", mappedBy="supplier", cascade={"all"})
     *
     * @JMS\MaxDepth(1)
     * @JMS\Groups({"original"})
     * @JMS\Type("ArrayCollection<ATE\SupplierDomain\Component\Listing\Listing>")
     */
    private $listings;

    /**
     * @JMS\PostDeserialize
     */
    public function __construct()
    {
        $this->listings = new ArrayCollection();

        parent::__construct();
    }
}
```

**Comment by bahatron** [comment]
gottta initialize variables on the parent!

will look into it. thank you

**Comment by bahatron** [comment]
You were right, found the issue within the version object. It's strange tho, since there are completely different objects.

Anyway, problem solved. Thank you!

```
<?php

namespace ATE\SupplierDomain\Model\Version\v3;

use JMS\Serializer\Annotation as JMS;
use ATE\SupplierDomain\Model\Version\VersionObject;
use ATE\SupplierDomain\Model\Entity\Supplier\Supplier as BaseSupplier;

class CustomerVersion3 extends SupplierVersion3 implements VersionObject
{
    public $type;

    /**
     * @JMS\Type("array<ATE\SupplierDomain\Component\Listing\Listing>")
     */
    public $listings;

    public $signedTerms;
    public $willReceiveMarketingEmails;

    public function __construct(BaseSupplier $supplier)
    {
        parent::__construct($supplier);

        $this->type = 'customer';

        $this->listings = $supplier->getListings(); // array
        $this->signedTerms = $supplier->getSignedTermsDate();
        $this->willReceiveMarketingEmails = $supplier->getWillReceiveMarketingEmails();
    }
}
```

**Comment by goetas** [comment]
:+1:
