### ISSUE TITLE
Bug? JMSSerializer events do not work for concrete types

### ISSUE THREAD

**Issue by SDPrio** [schmittjoh/JMSSerializerBundle#716]
I am trying to create an `EventSubscriber` for different serialization events using  `Symfony 3.4.21`, `JMSSerializer 2.1.0` and `JMSSerializerBundle 3.0.0`.

Problem is, that the subscribers only work if they are not registered for a concrete type. **Why is this?**

My setup:

    // src/AppBundle\EventListener\SerializationEventSubscriber.php
    use JMS\Serializer\EventDispatcher\Events;
    use JMS\Serializer\EventDispatcher\EventSubscriberInterface;
    use JMS\Serializer\EventDispatcher\PreSerializeEvent;
    use JMS\Serializer\EventDispatcher\ObjectEvent;

    class SerializationEventSubscriber implements EventSubscriberInterface {
        public static function getSubscribedEvents() {        
            return array(    	
                // Subscribe with NO specific class       
                array('event' => Events::PRE_SERIALIZE, 'method' => 'onPreSerialize_NoClass'),
                array('event' => Events::POST_DESERIALIZE, 'method' => 'onPostDeserialize_NoClass'),

  	
                // Subscribe WITH specific class       
                array('event' => Events::PRE_SERIALIZE, 'method' => 'onPreSerialize_Class', 'class' => 'AppBundle\Entity\MyEntity'),
                array('event' => Events::POST_DESERIALIZE, 'method' => 'onPostDeserialize_Class', 'class' => 'AppBundle\Entity\MyEntity'),
            );
        }

        public function onPreSerialize_NoClass(PreSerializeEvent $event) {
            // log...
        }

        public function onPostDeserialize_NoClass(PreSerializeEvent $event) {
            // log...
        }

        public function onPreSerialize_Class(PreSerializeEvent $event) {
            // log...
        }

        public function onPreSerialize_Class(PreSerializeEvent $event) {
            // log...
        }
    }

    // app/config/services.yml
    AppBundle\EventListener\SerializationEventSubscriber:
        tags:
            - { name: "jms_serializer.event_subscriber" }  

While first two handlers (defined with no specific class) are correctly called, the two handlers with a specific class are **not called**. 

If I check the class of the event object in the `..._NoClass` handlers, it perfectly matches the type used in the `..._Class` handlers.

According to the [docs][1] it should be no problem to define a handler for a specific class. **What is wrong with my config?**

---------------------------

I think the cause of the problem can be found within `JMS\Serializer\EventDispatcher\EventDispatcher`. The second parameter of the `initializeListeners` is `$loweredClass` which is compared to the `$listener[1]`. 

The problem is, that `$loweredClass` does **NOT** contain the lower case version of the class FQCN but the "normal" mixed case FQCN. So in my example `AppBundle\Entity\MyEntity` is compared to `appbundle\entity\myentity` which fails of course. Thus no listeners is found...

The listeners are set to the `EventDispatcher` using the `setListeners()` methods, which seems to be called from the `appProdProjectContainer.php` (the cache). So is there something wrong with the cache (contains the FQCNs in lower case instead of mixed case) or with the `EventDispatcher` (compares mixed to lower case is always false). 

Thanks!

    

  [1]: http://jmsyst.com/libs/serializer/master/event_system#register-an-event-listener-or-subscriber

**Comment by SDPrio** [comment]
> ...the variable is called $loweredClass but the actual class name is never lowercased.

This is exactly the problem. `$loweredClass` contains a mixed case string and is then compared to `$listener[1]` which DOES contain the lower case class name. 

            if (null !== $listener[1] && $loweredClass !== $listener[1]) 

Because this comparison fails no listener is found and thus the event not handled. 

Since the variable is called `$loweredClass` it seems to be correct that a lower case value is expected. This makes sense, since `$listener[1]` contains a lower case string. However the method is called from `hasListeners` which does not make sure, that a lower case value is passed.

**Comment by goetas** [comment]
Can you point me where `$listener[1]` is set to lowercase?

**Comment by SDPrio** [comment]
`initializeListeners` loops through `$this->listeners[$eventName]`. In my case `$this->listeners[$eventName]` is set/initalized in `setListeners`.

To find out where `setListeners` is called from I simply throw an exception within this setter and look at the stack trace:

    #0 /.../project/var/cache/prod/ContainerLdarxf2/appProdProjectContainer.php(2169): JMS\\Serializer\\EventDispatcher\\EventDispatcher->setListeners(Array)
    #1 /.../project/var/cache/prod/ContainerLdarxf2/appProdProjectContainer.php(2924): ContainerLdarxf2\\appProdProjectContainer->getJmsSerializerService()
    #2 /.../project/var/cache/prod/ContainerLdarxf2/appProdProjectContainer.php(3593): ContainerLdarxf2\\appProdProjectContainer->getFosRest_SerializerService()
    #3 /.../project/var/cache/prod/ContainerLdarxf2/appProdProjectContainer.php(3581): ContainerLdarxf2\\appProdProjectContainer->getSensioFrameworkExtra_Converter_ManagerService()
    #4 /.../project/var/cache/prod/ContainerLdarxf2/appProdProjectContainer.php(1996): ContainerLdarxf2\\appProdProjectContainer->getSensioFrameworkExtra_Converter_ListenerService()
    #5 /.../project/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(229): ContainerLdarxf2\\appProdProjectContainer->ContainerLdarxf2\\{closure}()
    #6 /.../project/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(61): Symfony\\Component\\EventDispatcher\\EventDispatcher->sortListeners('kernel.controll...')
    #7 /.../project/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(128): Symfony\\Component\\EventDispatcher\\EventDispatcher->getListeners('kernel.controll...')
    #8 /.../project/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(43): Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->getListeners('kernel.controll...')
    #9 /.../project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.controll...', Object(Symfony\Component\\HttpKernel\\Event\\FilterControllerEvent))
    #10 /.../project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\Request), 1)
    #11 /.../project//vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
    #12 /.../project/web/app.php(19): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
    #13 {main}


The code within `` contains the lower case class names:

    2 => array(0 => array(0 => 'AppBundle\\EventListener\\SerializationEventSubscriber', 1 => 'onPreSerialize_Class'), 1 => 'appbundle\\entity\\myentity', 2 => NULL, 3 => NULL)

**Comment by SDPrio** [comment]
Again: Why should the variable be called `$loweredClass` if now lowered class would be expected? Thus it seems correct that `$listener[1]` user lower FQCN and it seems to be a but that a mixed case value is passed.

**Comment by goetas** [comment]
Was lowercased in jms v1, in v2 not anymore.

The interesting thing to figure out is why `appbundle\\entity\\myentity'` is lowercased...

**Comment by SDPrio** [comment]
Well, I don't know in detail how the cache operates and why lower case is used here. 

> Was lowercased in jms v1, in v2 not anymore.

I was not able to find the exact commit where this was changed. Looks as it always was `$lowerdclass`

**Comment by goetas** [comment]
> The interesting thing to figure out is why appbundle\\entity\\myentity' is lowercased...

**Comment by SDPrio** [comment]
As a workaround I defined the listeners without a specific class and then filter for the class within the handlers. This is looks bad but works. Is there any better solution?

    public static function getSubscribedEvents() {        
        return array(    	
            array('event' => Events::PRE_SERIALIZE, 'method' => 'onPreSerialize_NoClass'),
            array('event' => Events::POST_DESERIALIZE, 'method' => 'onPostDeserialize_NoClass'),
        );
    }

    private $acceptedClasses = array(
        'AppBundle\Entity\MyEntity',
        ...
    );

    public function onPreSerialize_NoClass(PreSerializeEvent $event) {
        if (!$event || !$event->getObject())
            return;
            
        $class = get_class($event->getObject());
        
        if (in_array($class, $this->acceptedClasses)) {
            $this->onPostDeserialize_Class($event);
    }

**Comment by goetas** [comment]
it will be great if you can figureout where it gets lowercased...

**Comment by SDPrio** [comment]
As mentioned I am not an expert on how the cache works. Thus I have no idea why it uses lowercase FQCN here. 

I don't even know if the way the cache operates in this case is controlled by Symfony or the JMSSerializer(Bundle). 

Any idea or suggestions where to start looking?

**Comment by goetas** [comment]
Can you try to check the value of $class in https://github.com/schmittjoh/JMSSerializerBundle/blob/37d9568901212c7e67cd1d6431277fcf46ef992f/DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php#L55 and the value of `listeners` in https://github.com/schmittjoh/JMSSerializerBundle/blob/37d9568901212c7e67cd1d6431277fcf46ef992f/DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php#L79

?

**Comment by SDPrio** [comment]
Maybe this is the problem: I am using bundle version 3.0.0 and this version uses 

    $class = isset($eventData['class']) ? strtolower($eventData['class']) : null;

This was changed in [3.1.0](https://github.com/schmittjoh/JMSSerializerBundle/commit/2cb36ae934d2c74a7a7c23bae5270aef8a3a05aa#diff-fd5276ac8fd3b6a11901c103c024148eL55) to

     $class = isset($eventData['class']) ? $eventData['class'] : null;
