### ISSUE TITLE
Deprecated error with Twig 2.7.2

### ISSUE THREAD

**Issue by barell** [schmittjoh/JMSSerializerBundle#731]
I use Symfony 3.4.22 and just updated my Twig to 2.7.2 as there was vulnerability discovered in version 2.5.0.

After upgrading Twig, I started to see deprecated warnings: 

`Using the "Twig_RuntimeLoaderInterface" class is deprecated since Twig version 2.7, use "Twig\RuntimeLoader\RuntimeLoaderInterface" instead.`

Not sure if this is related to bundle or serializer itself but this is full error trace:
```
Using the "Twig_RuntimeLoaderInterface" class is deprecated since Twig version 2.7, use "Twig\RuntimeLoader\RuntimeLoaderInterface" instead.
Stack trace:
#0 vendor/twig/twig/lib/Twig/RuntimeLoaderInterface.php(7): trigger_error('Using the "Twig...', 16384)
#1 vendor/composer/ClassLoader.php(444): include('/app/vendor/twi...')
#2 vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/app/vendor/com...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Twig_RuntimeLoa...')
#4 [internal function]: spl_autoload_call('Twig_RuntimeLoa...')
#5 vendor/jms/serializer-bundle/DependencyInjection/Compiler/TwigExtensionPass.php(14): interface_exists('Twig_RuntimeLoa...')
#6 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(141): JMS\SerializerBundle\DependencyInjection\Compiler\TwigExtensionPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(788): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#8 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(637): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#9 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
```

So I was trying to upgrade jms/serializer-bundle to latest version but the error didn't disappear.

**Comment by goetas** [comment]
fixed buy https://github.com/schmittjoh/JMSSerializerBundle/pull/733
