### ISSUE TITLE
Unable to use inside Shopware plugin

### ISSUE THREAD

**Issue by dtrunk90** [schmittjoh/JMSSerializerBundle#951]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no

Whenever I try to install my shopware plugin I'm getting this huge stack trace:
```
Fatal error: During inheritance of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator, while autoloading Symfony\Component\Finder\SplFileInfo: Uncaught ErrorException: include(/var/www/html/vendor/composer/../symfony/finder/SplFileInfo.php): Failed to open stream: No such file or directory in /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php:300
Stack trace:
#0 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(300): Composer\Util\ErrorHandler::handle()
#1 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(300): include()
#2 /var/www/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(24): Symfony\Component\ErrorHandler\DebugClassLoader->loadClass()
#3 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(300): include('...')
#4 /var/www/html/vendor/symfony/finder/Finder.php(790): Symfony\Component\ErrorHandler\DebugClassLoader->loadClass()
#5 /var/www/html/vendor/symfony/finder/Finder.php(671): Symfony\Component\Finder\Finder->searchInDirectory()
#6 /var/www/html/vendor/symfony/finder/Finder.php(742): Symfony\Component\Finder\Finder->getIterator()
#7 /var/www/html/vendor/composer/composer/src/Composer/Util/Filesystem.php(65): Symfony\Component\Finder\Finder->count()
#8 /var/www/html/vendor/composer/composer/src/Composer/Installer/BinaryInstaller.php(129): Composer\Util\Filesystem->isDirEmpty()
#9 /var/www/html/vendor/composer/composer/src/Composer/Installer/LibraryInstaller.php(179): Composer\Installer\BinaryInstaller->removeBinaries()
#10 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(487): Composer\Installer\LibraryInstaller->update()
#11 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(378): Composer\Installer\InstallationManager->update()
#12 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Composer\Installer\InstallationManager->Composer\Installer\{closure}()
#13 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(377): React\Promise\FulfilledPromise->then()
#14 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(319): Composer\Installer\InstallationManager->executeBatch()
#15 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(218): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#16 /var/www/html/vendor/composer/composer/src/Composer/Installer.php(837): Composer\Installer\InstallationManager->execute()
#17 /var/www/html/vendor/composer/composer/src/Composer/Installer.php(649): Composer\Installer->doInstall()
#18 /var/www/html/vendor/composer/composer/src/Composer/Installer.php(298): Composer\Installer->doUpdate()
#19 /var/www/html/vendor/composer/composer/src/Composer/Command/RequireCommand.php(498): Composer\Installer->run()
#20 /var/www/html/vendor/composer/composer/src/Composer/Command/RequireCommand.php(340): Composer\Command\RequireCommand->doUpdate()
#21 /var/www/html/vendor/symfony/console/Command/Command.php(279): Composer\Command\RequireCommand->execute()
#22 /var/www/html/vendor/symfony/console/Application.php(1029): Symfony\Component\Console\Command\Command->run()
#23 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#24 /var/www/html/vendor/composer/composer/src/Composer/Console/Application.php(394): Symfony\Component\Console\Application->doRun()
#25 /var/www/html/vendor/symfony/console/Application.php(167): Composer\Console\Application->doRun()
#26 /var/www/html/vendor/composer/composer/src/Composer/Console/Application.php(148): Symfony\Component\Console\Application->run()
#27 /var/www/html/vendor/shopware/core/Framework/Plugin/Composer/CommandExecutor.php(43): Composer\Console\Application->run()
#28 /var/www/html/vendor/shopware/core/Framework/Plugin/PluginLifecycleService.php(705): Shopware\Core\Framework\Plugin\Composer\CommandExecutor->require()
#29 /var/www/html/vendor/shopware/core/Framework/Plugin/PluginLifecycleService.php(126): Shopware\Core\Framework\Plugin\PluginLifecycleService->executeComposerRequireWhenNeeded()
#30 /var/www/html/vendor/shopware/core/Framework/Plugin/Command/Lifecycle/PluginInstallCommand.php(69): Shopware\Core\Framework\Plugin\PluginLifecycleService->installPlugin()
#31 /var/www/html/vendor/symfony/console/Command/Command.php(279): Shopware\Core\Framework\Plugin\Command\Lifecycle\PluginInstallCommand->execute()
#32 /var/www/html/vendor/symfony/console/Application.php(1047): Symfony\Component\Console\Command\Command->run()
#33 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(123): Symfony\Component\Console\Application->doRunCommand()
#34 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#35 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\Component\Console\Application->doRun()
#36 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#37 /var/www/html/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(49): Symfony\Component\Console\Application->run()
#38 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
#39 /var/www/html/bin/console(17): require_once('...')
#40 {main} in /var/www/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 24
19:32:57 CRITICAL  [php] Fatal Error: During inheritance of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator, while autoloading Symfony\Component\Finder\SplFileInfo: Uncaught ErrorException: include(/var/www/html/vendor/composer/../symfony/finder/SplFileInfo.php): Failed to open stream: No such file or directory in /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php:300
Stack trace:
#0 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(300): Composer\Util\ErrorHandler::handle()
#1 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(300): include()
#2 /var/www/html/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(24): Symfony\Component\ErrorHandler\DebugClassLoader->loadClass()
#3 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(300): include('...')
#4 /var/www/html/vendor/symfony/finder/Finder.php(790): Symfony\Component\ErrorHandler\DebugClassLoader->loadClass()
#5 /var/www/html/vendor/symfony/finder/Finder.php(671): Symfony\Component\Finder\Finder->searchInDirectory()
#6 /var/www/html/vendor/symfony/finder/Finder.php(742): Symfony\Component\Finder\Finder->getIterator()
#7 /var/www/html/vendor/composer/composer/src/Composer/Util/Filesystem.php(65): Symfony\Component\Finder\Finder->count()
#8 /var/www/html/vendor/composer/composer/src/Composer/Installer/BinaryInstaller.php(129): Composer\Util\Filesystem->isDirEmpty()
#9 /var/www/html/vendor/composer/composer/src/Composer/Installer/LibraryInstaller.php(179): Composer\Installer\BinaryInstaller->removeBinaries()
#10 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(487): Composer\Installer\LibraryInstaller->update()
#11 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(378): Composer\Installer\InstallationManager->update()
#12 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Composer\Installer\InstallationManager->Composer\Installer\{closure}()
#13 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(377): React\Promise\FulfilledPromise->then()
#14 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(319): Composer\Installer\InstallationManager->executeBatch()
#15 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(218): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#16 /var/www/html/vendor/composer/composer/src/Composer/Installer.php(837): Composer\Installer\InstallationManager->execute()
#17 /var/www/html/vendor/composer/composer/src/Composer/Installer.php(649): Composer\Installer->doInstall()
#18 /var/www/html/vendor/composer/composer/src/Composer/Installer.php(298): Composer\Installer->doUpdate()
#19 /var/www/html/vendor/composer/composer/src/Composer/Command/RequireCommand.php(498): Composer\Installer->run()
#20 /var/www/html/vendor/composer/composer/src/Composer/Command/RequireCommand.php(340): Composer\Command\RequireCommand->doUpdate()
#21 /var/www/html/vendor/symfony/console/Command/Command.php(279): Composer\Command\RequireCommand->execute()
#22 /var/www/html/vendor/symfony/console/Application.php(1029): Symfony\Component\Console\Command\Command->run()
#23 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#24 /var/www/html/vendor/composer/composer/src/Composer/Console/Application.php(394): Symfony\Component\Console\Application->doRun()
#25 /var/www/html/vendor/symfony/console/Application.php(167): Composer\Console\Application->doRun()
#26 /var/www/html/vendor/composer/composer/src/Composer/Console/Application.php(148): Symfony\Component\Console\Application->run()
#27 /var/www/html/vendor/shopware/core/Framework/Plugin/Composer/CommandExecutor.php(43): Composer\Console\Application->run()
#28 /var/www/html/vendor/shopware/core/Framework/Plugin/PluginLifecycleService.php(705): Shopware\Core\Framework\Plugin\Composer\CommandExecutor->require()
#29 /var/www/html/vendor/shopware/core/Framework/Plugin/PluginLifecycleService.php(126): Shopware\Core\Framework\Plugin\PluginLifecycleService->executeComposerRequireWhenNeeded()
#30 /var/www/html/vendor/shopware/core/Framework/Plugin/Command/Lifecycle/PluginInstallCommand.php(69): Shopware\Core\Framework\Plugin\PluginLifecycleService->installPlugin()
#31 /var/www/html/vendor/symfony/console/Command/Command.php(279): Shopware\Core\Framework\Plugin\Command\Lifecycle\PluginInstallCommand->execute()
#32 /var/www/html/vendor/symfony/console/Application.php(1047): Symfony\Component\Console\Command\Command->run()
#33 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(123): Symfony\Component\Console\Application->doRunCommand()
#34 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#35 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\Component\Console\Application->doRun()
#36 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#37 /var/www/html/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(49): Symfony\Component\Console\Application->run()
#38 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
#39 /var/www/html/bin/console(17): require_once('...')
#40 {main} ["exception" => Symfony\Component\ErrorHandler\Error\FatalError^ { …}]
```

After that the whole container is broken and `bin/console` cannot be run anymore.

## Steps required to reproduce the problem

See reproducer repository [here](https://github.com/dtrunk90/JMSSerializerBundle-issue-951)

## Expected Result

* Shopware plugin should be installable without issues

## Actual Result

* Exception when trying to install the Shopware plugin

**Comment by scyzoryck** [comment]
I do not see anything related to JMS in the log. It looks like symfony / shopware issue - I would suggest to look for the help in the shopware groups :) 

Best, Marcin
